function(get_os_release_info _os_name _os_version)
    file(STRINGS "/etc/os-release" OS_RELEASE)
    set(_os_name_var "")
    set(_os_version_var "")
    foreach(_str ${OS_RELEASE})
        if("${_str}" MATCHES "^ID=(.+)$")
            # message("match is: ${CMAKE_MATCH_1}")
            set(_os_name_var ${CMAKE_MATCH_1})
        endif()
        if("${_str}" MATCHES "^VERSION_ID=\"(.+)\"$")
            message("match is: ${CMAKE_MATCH_1}")
            set(_os_version_var ${CMAKE_MATCH_1} PARENT_SCOPE)
        endif()
    endforeach()
    set(${_os_name} ${_os_name_var} PARENT_SCOPE)
    set(${_os_version} ${_os_version_var} PARENT_SCOPE)
endfunction()

include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_VERSION_MAJOR "${VisionRC_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${VisionRC_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${VisionRC_VERSION_PATCH}")
if(LINUX)
    get_os_release_info(OS_NAME OS_VERSION)
    set(CPACK_GENERATOR "TGZ")
    if("${OS_NAME}" STREQUAL "ubuntu")
        list(APPEND CPACK_GENERATOR "DEB")
    endif()
    if("${OS_NAME}" STREQUAL "centos")
        list(APPEND CPACK_GENERATOR "RPM")
    endif()
    set(CPACK_SOURCE_GENERATOR "TGZ")
else()
    set(CPACK_GENERATOR "ZIP")
    set(CPACK_SOURCE_GENERATOR "ZIP")
endif()

# DEB package specifics
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libsdl2-2.0-0, libsdl2-mixer-2.0-0, libopencv-dev, libxcb-cursor0, libgl1-mesa-dri")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "VisionRC")

# RPM package specifics
#set(CPACK_RPM_PACKAGE_DEPENDS "")

include(CPack)

