FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
        build-essential cmake g++ wget unzip ninja-build \
        libsdl2-dev libsdl2-mixer-dev \
        libopencv-dev \
        libgl1-mesa-dev

